### ISSUE TITLE
Comparison of sets fails

### ISSUE THREAD

**Issue by noamelf** [hynek/attrs#101]
See following code sample:
```python
import attr

@attr.s()
class A:
    x = attr.ib()
    y = attr.ib(cmp=False)

a1 = A(1, 3) 
a2 = A(1, 4)
assert a1 == a2

assert set([a1]) == set([a2])
```

I would suspect that both assertions will be correct, but the one that compares the class inside a set fails . 

This seems like a bug or an inconsistent behaviour with the way sets work. 

#### Versions:
Python 2.7.12
attrs master branch (`61d66e4d66fca1d0c9ad4cdecdadb3731eb52ac`)

**Comment by hynek** [comment]
Sets (like dicts) use hashes, not comparisons.  Try setting `y`’s `hash=False`.

**Comment by noamelf** [comment]
Thanks @hynek that solved it! I think more people might be confused by this difference between `hash` and `cmp` and just expect `cmp` to take care of both. Do you think it makes sense that the default behaviour will be that setting `cmp` will also set `hash` behind the scene and vice versa?

**Comment by hynek** [comment]
I’m afraid even thinking about that breaks some people’s software. :)  There’s def the need for the current “low-level” API.  Maybe one day we’ll add pre-configured class and attributes types.  But we really can’t change fundamental APIs. :)
