### ISSUE TITLE
override asdict in recursive calls

### ISSUE THREAD

**Issue by lukpueh** [hynek/attrs#103]
Hi,
first of all, thanks for providing this nice package!
I have the following issue. I'd like to use `asdict` recursively and override the default behavior at some point in the recursion, to return e.g. the `__repr__` of a class instead of a dictionary. Any idea on how to do this?

Here is a minimal example:
```python
@attr.s()
class Foo():
 x = attr.ib()
 bar = attr.ib()

@attr.s()
class Bar():
  x = attr.ib()

  def __repr__(self):
    return "This is what I want instead"

attr.asdict(Foo(x="foo", bar=Bar(x="bar")))

# The resulting dict should look like this:
# { x : "foo", bar : "This is what I want instead" }
```

Any help would be highly appreciated!

**Comment by hynek** [comment]
That doesn’t look like something `asdict` will ever support.   It has `dict` in its name for a reason. :)

Please note that `asdict` is just a function so if you want some specific behavior, you can just write your own: https://github.com/hynek/attrs/blob/1b419e304b01bbbcb1d0d7b0515efdbc7de73588/src/attr/_funcs.py#L10-L67

**Comment by nrbnlulu** [comment]
Here is a workaround
```py
def asdict_hashable(hashable: 'HashAble') -> dict:
    """enables to override attrs asdict() per class."""
    ret = attrs.asdict(hashable, recurse=False)
    hashable.__update_dict__(ret)
    for k, v in ret.items():
        if isinstance(v, HashAble):
            v = asdict_hashable(v)
            ret[k] = v
    return ret

class HashAble:
    """Must be attrs instance"""
    def __update_dict__(self, org: dict) -> None:
        ...

    def asdict(self) -> dict:
        return asdict_hashable(self)
```
