### ISSUE TITLE
Should attr.make_class produce an attr.asdict compatible object

### ISSUE THREAD

**Issue by danodonovan** [hynek/attrs#108]
For example

```python
t = attr.make_class("Test", {"this": "that"})
attr.asdict(t)
```

produces 

> NotAnAttrsClassError: <type 'type'> is not an attrs-decorated class.

Looking at `t` it has the `__attr_attr__` attribute, but it's an empty tuple (ie with no `Attribute` instance).

**Comment by hynek** [comment]
First of all, you got the make_class call wrong.  It's either a list of strings or a dict of str → attr.ib().

Then, `t` is a class (named Test) and `attr.asdict` takes an instance (of `t`):

```
>>> t = attr.make_class("Test", ["this", "that"])
>>> attr.asdict(t(1, 2))
{'this': 1, 'that': 2}
```

I suppose you thought that `make_class` also creates instances in one go?

**Comment by danodonovan** [comment]
Yup - my confusion. Thanks for the clarification!
