### ISSUE TITLE
Multiple validators?

### ISSUE THREAD

**Issue by mjmare** [hynek/attrs#11]
The docs mentions "a bunch of validators", but they ar not there yet, right? Am I correct that there is no way of supplying multiple validators? Of course one could write custom validators, but it seems more useful to be able to compose validators.

**Comment by mjmare** [comment]
Oh, and if one wants an attrib to be required, that has to be implemented with a validator?

**Comment by hynek** [comment]
`attrs` comes with two validators: https://attrs.readthedocs.org/en/stable/api.html#validators . Calling them a “bunch” may be a bit of a stretch but I didn’t want to reword once they grow. :)

I had some code in place for `and`ing and `or`ing validators but it felt a bit academic so I took it out for now again until I come up with a compelling use case.

Attributes are always required unless you supply a default value.

**Comment by mjmare** [comment]
and/or validators seem pretty useful to me in order to make validators more granular. But other validator will likely be needed more, like ranges, or select from list or...

**Comment by econchick** [comment]
@mjmare (not a maintainer, just an avid user of `attrs`) - you can write & supply your own validators and not rely on @hynek to write more default ones.  

For instance, I've written a lot of validators for [ramlfications](https://github.com/spotify/ramlfications) - an example: [the version of the RootNode](https://github.com/spotify/ramlfications/blob/master/ramlfications/raml.py#L52) validates with [this function](https://github.com/spotify/ramlfications/blob/master/ramlfications/validate.py#L17).

Not sure if that helps at all :smile:  but attrs' validation is definitely one of the main reasons I chose this library when writing my library.

**Comment by hynek** [comment]
…and you can totally put them on PyPI either if you think they’re generally useful. :)  I’m trying to learn from the mistakes I did with characteristic and keep the scope small on purpose while giving users ways to extend attrs to their liking.
