### ISSUE TITLE
Support __str__

### ISSUE THREAD

**Issue by mithrandi** [hynek/attrs#112]
Exceptions use `__str__` instead of `__repr__` for formatting; this is unfortunate for defining exceptions with attrs, because the default `__str__` will print out nothing which is very useless.

What do you think about an extra option to define `__str__` the same as `__repr__`?

**Comment by hynek** [comment]
Yeah I’ve run into that too & resorted to setting `__str__` to `__repr__` by hand before.  I guess we can add a `str=False`.

**Comment by hynek** [comment]
I presume this is what you wanted?

**Comment by mithrandi** [comment]
Yup! :+1:
