### ISSUE TITLE
combine frozen with init

### ISSUE THREAD

**Issue by peendebak** [hynek/attrs#113]
Is there a way to combine the `frozen` and `init` parameter of `attr.s`? An example:

```
import attr

@attr.s(init=False, frozen=True)
class myclass (object):    
        def __init__(self, a, b=1, c=2):
            self.a=a
            self.b=b
            self.c=c
        def test(self):
            print(self.a)
            print(self.b)
            print(self.c)
      
v=myclass(10,20)
v.test() # should be fine
v.a=10 # should be fine
v.d=100 # should generate an error
```

The example generates an error `FrozenInstanceError: can't set attribute`

**Comment by hynek** [comment]
This is not possible by the way frozen classes are implemented.  You’d have to do our [setattr-circumventing dance](https://attrs.readthedocs.io/en/stable/how-does-it-work.html#immutability) yourself.

**Comment by peendebak** [comment]
@hynek I could not find how to do this with the provided link. After some searching I used the solution by Yoann on stackoverflow [freeze class with decorator](http://stackoverflow.com/a/29368642).

**Comment by hynek** [comment]
attrs goes a different way for a variety of reasons:

```
>>> import attr

>>> @attr.s(frozen=True)
... class C:
...     x = attr.ib()

>>> import inspect

>>> print(inspect.getsource(C.__init__))
def __init__(self, x):
    _setattr = _cached_setattr.__get__(self, self.__class__)
    _setattr('x', x)


>>> print(inspect.getsource(C.__setattr__))
def _frozen_setattrs(self, name, value):
    """
    Attached to frozen classes as __setattr__.
    """
    raise FrozenInstanceError()
```
