### ISSUE TITLE
Handling of default values (and `assoc`)

### ISSUE THREAD

**Issue by pstch** [hynek/attrs#115]
Hi,

I've been playing around with attrs lately, and removed a lot of boilerplate code using it. I wanted to suggest a feature : allowing to separate the storage of given and default values.

This would allow to create an attrs instance using values from an instance that has different default values. Currently, doing this will result in the former instance receiving all values from the latter, including the default ones, thus overriding the changed defaults in the new class.

I realize that most Python code sets the default values as attribute values directly in `__init__`, but sometimes I have to only provide the default when really using the value, to be able to derive the object without inheriting default values.

I think this change is non-backwards compatible, and would have to be implemented with an additional 
option.

Would support for this be accepted ? Or did I simply miss an easier way to do this ?

**Comment by hynek** [comment]
I’m not sure I understand?  Default values are part of the class/type definition and `assoc` always returns the same type.  Could you give a concrete example?

**Comment by pstch** [comment]
Ah yes, I misunderstood `assoc`. I'm starting to reconsider this idea, I'm not sure that it does fall in the scope of this module. An example would be:

```
@attr.s
class A:
    foo = attr.ib(default=4)
    bar = attr.ib(default=8)
  

@attr.s
class B:  
    foo = attr.ib(default=16)
    bar = attr.ib(default=32)

a = A(foo=42)
b = B(**attr.asdict(a))

```

In this example, with `attrs`, `b` would be `B(foo=42, bar=8)`. I'm looking for a way to create an instance of `B` with **only the values that were actually provided to `A`**, so that `b` is `B(foo=42, bar=32)`.

**Comment by hynek** [comment]
You’re kind of looking for ways to work around types in attrs which I’d strongly argue against.  Even weak types are a great way to make software more robust.

If you have a special need that warrants such conversions you can just write a function that takes an A and returns a B. :)  No need for any attrs magic whatsoever.
