### ISSUE TITLE
broken link in docs

### ISSUE THREAD

**Issue by tacaswell** [hynek/attrs#117]
https://attrs.readthedocs.io/en/stable/overview.html

The 'edit on github' link on the top right links to https://github.com/hynek/attrs/blob/699f9097355624ef9f64305927d4e776a7db6fac/docs/overview.rst which is a 404.

**Comment by hynek** [comment]
I’m getting this report on each project of mine and I don’t know of a way to fix it.  It seems to be related to the stable thingie.  Only solution I can think of is to hack the templates to get rid of the edit button. :(
