### ISSUE TITLE
First look

### ISSUE THREAD

**Issue by guettli** [hynek/attrs#123]
Hi,

here is some feedback.

I like your idea. This way you can avoid to code boring `__init__()` methods: Nice

Some small things don't match according to my first sight. It depends on your goal. If you are a geek, they are not important. If you want WAF, then they are.

The github repo is called "attrs", but the import is called "attr".

"attr.ib()" looks like black magic. What is "ib"? It would be nice if a new comer could understand this code without explanation or looking up docs.

Same for "attr.s".

Example code from pypi age: `i = C(x=1, y=2)`

If you want WAF, then I would call "C" "Point" and "i" "point".

Don't get me wrong: I like the intention of this module very much!

**Comment by hynek** [comment]
Although I have no idea what WAF means (all I found is “wife acceptance factor” which I hope is not what you meant) I’ve done some of your recommendations.   As for attr.s/attr.ib: I can’t explain it in any other way than writing it down. :)
