### ISSUE TITLE
Metaclass-based augmentation

### ISSUE THREAD

**Issue by p-himik** [hynek/attrs#132]
After some pondering on #102, I tried to reimplement attrs using metaclasses, and I even got everything working. Well, according to the tests.
I now understand that metaclasses alone won't make `TypeError` from that issue go away, but they still have a very nice property - every augmentation gets inherited.
E.g. right now if I have a few classes that are all inherited from some parent class, in order to have e.g. slots enabled on every one of them, I have to write `@attr.s(slots=True)` for each of them.
With metaclasses, I have to do this only once - on the parent class.
But the changes I made obviously change things about which tests are not aware (yet?). Currently, if I add a child class with no `@attr.s` decorator, no augmentation will be performed. Although I find it very doubtful that some people rely on this, it still is a possibility.

Personally, I'd love to have this inherited augmentation, since one of my projects involves tens to hundreds of classes (albeit sometimes these classes are generated) that use attrs with the exact same parameters and that are inherited from a single parent.
And I think that it's possible to avoid the aforementioned potential breakage, if necessary, by a separate parameter to `attr.s`.

What are your thoughts?

**Comment by hynek** [comment]
I think not inheriting slots was a conscious decision (@Tinche?) and it’s not like it’s impossible to implement without meta classes.  You just look at the superclass like we do for attributes and set it in the current one.  Although I think that would be a breaking change?

**Comment by p-himik** [comment]
```python
@attr.s(slots=True)
class A:
    x = attr.ib()


class B(A):
    y = attr.ib()
```

How and where exactly do you look at the superclass, if `B` doesn't have a decorator at all?

**Comment by hynek** [comment]
oh i see you want to inherit the attrs-ness too?  I don’t see that as a downside TBH.  I like explicit APIs that change as little as possible in each usage.

**Comment by p-himik** [comment]
Not sure I understand your last sentence correctly.
So, should I create a pull-request?

**Comment by hynek** [comment]
No, sorry but there will be no metaclasses in attrs ever.   One of the initial design goals was to avoid them and I believe there’s plenty metaclassy alternatives out there…
