### ISSUE TITLE
Filtering 'private' attributes

### ISSUE THREAD

**Issue by kochuyt** [hynek/attrs#137]
Maybe there is already an easy (meaning minimal typing ;^) way to do this but...

As a (somewhat) business / data science type of user (so not a hard core dev) I would be thrilled if I could include/exclude 'private' attributes from asdict/astuple results with a simple option

So if I have a class like this
```
@attr.s
class Example():
        an_attribute = attr.ib()
        _a_private_attribute = attr.ib()

example = Example('a', 'lark')
```

Then if I want a dict with all attributes I do
```
attr.asdict(example, privates=True)
... {'an_attribute': 'a', '_a_private_attribute': 'lark'}
```

And if I want the dict without the 'private' attributes I do
```
attr.asdict(example, privates=False)
... {'an_attribute': 'a'}
```

Reasons for suggesting above: essentially, I hate non-value-add typing (which is why I already love attr ;^)

I often use attr in the context of pre-processing file-based data before passing it in into a pandas DataFrame. And sometimes (a lot of times actually) that means the input data has many columns that I do not actually need in the DataFrame.

Sure, I could do it all in pandas, loading all columns to the DataFrame and then drop those columns I do not need... meh, lots of typing (and processing) not really adding value

Alternatively I could also use the existing atrr.asdict filter option (and attr.filters.include/exclude) but let's be honest... it's no fun (and not exactly readable) to exclude say maybe 3+ (I often have 10+) attributes this way... and meh, loads of typing not adding any additional value...

Unless of course one likes typing/reading things like
```
... filter=attr.filters.exclude(attr.fields(Example)._a_private_attribute, attr.fields(Example)._another_private, attr.fields(Example)._third_private, attr.fields(Example)._one_more_private) ...
```

Above suggestion plays on Python convention of marking 'private' attributes with _.
As such
- it should be easy to understand the intention of the one who wrote the class for anyone having (even limited) experience with Python
- functional change would be limited to the asdict/astuple functions, adding the private keyword (and logic)
- private option can default to True to ensure backwards compatibility

**Comment by hynek** [comment]
Filters get the attribute as first argument so shouldn’t something like this work?

```python
def no_privates(a, _):
    return not a.name.startswith("_")
```

**Comment by kochuyt** [comment]
@hynek: I tried your suggestion and it works, so it is certainly a solution to my need, thanks! \o/

As said, I am far from a true dev guy (certainly in Python), so your suggestion is typically something I would not think of myself. So extra thanks for the quick reply and for teaching me ;^)

That being said, your suggestion in a way does assume the user of attr is sufficiently knowledgeable about some 'internal' attr stuff (or savvy/confident enough to have a look at the attr code...)

So maybe adding a 'no_private' keyword to the asdict/astuple API is still something worth considering (or am I pushing my luck here?).

**Comment by hynek** [comment]
Heh there’s nothing internal going on here; it’s all documented along with the filter argument [here](https://attrs.readthedocs.io/en/stable/api.html#attr.asdict) (and [here](https://attrs.readthedocs.io/en/stable/api.html#attr.Attribute)) and also in the [relevant example](https://attrs.readthedocs.io/en/stable/examples.html#converting-to-collections-types).

Adding another argument to asdict is certainly possible but since this is quite literally a one-liner and API-changes are mostly permanent, I try to show as much restraint as possible.

If anything, we could consider to add a no_privates filter to the `attr.validators` module.

**Comment by kochuyt** [comment]
Oh, you mean I should read the docs more attentively (you have a very valid point there ;^)

I can understand the restraint you show on adding options to the API, especially for something like this which is  very straightforward and simple to add (yes, in hindsight I must admit you are right).
As a user I also like uncluttered APIs better than ones that offer countless of options (most of which typically only confuse me).

So let's forget about my suggestion, and keep attrs as easy to use as possible (even for people like me). It's quite great as it is, you're right in not wanting to mess that up.

**Comment by BrendanSimon** [comment]
This was my exact use case and I thought the suggestion made a lot of sense.  Yes, it's not as generic as a filter, but attrs also includes common case helpers (include and exclude, which is for types only from what I can work out), so maybe a a common helper for privates might be useful (if it's common enough).

Is there any additional argument in `attr.ib()` that can be set to include/exclude it from `astuple()` and/or `asdict()`, etc ??

The "example relevant" example mentioned isn't explicit enough or easy enough for some people to get their head around - especially for `astuple()`.  Maybe adding a further simpler example for `astuple()` and/or `asdict()` to omit private attributes might be a good step.

filter function or lambda?

**Comment by hynek** [comment]
include/exclude work on both types and attributes (you can pass a mixed list).

It wold be trivial to add a `no_privates` helper to attr.filters if anyone cared enough.
