### ISSUE TITLE
Factory not creating new instance of attr-decorated class

### ISSUE THREAD

**Issue by ryantuck** [hynek/attrs#141]
Using `attr.ib(default=attr.Factory(MyClass))` does not work as expected if `MyClass()` is decorated by `@attr.s`, but does work normally with regular classes.

```python
import attr

@attr.s
class A(object):

    x = attr.ib(default=[])


class B(object):

    def __init__(self):
        self.x = []


@attr.s
class C(object):

    a = attr.ib(default=attr.Factory(A))
    b = attr.ib(default=attr.Factory(B))

    def update(self):
        self.a.x.append('a')
        self.b.x.append('b')


print 'c1'
c1 = C()
c1.update()
print c1.a.x
print c1.b.x

print 'c2'
c2 = C()
print c2.a.x
print c2.b.x

print 'equality tests'
print c1.a == c2.a
print c1.b == c2.b
```

Produces:

```
c1
['a']
['b']
c2
['a']
[]
equality tests
True
False
```

Is this actually a bug? Or am I not approaching `Factory` creation properly?

**Comment by hynek** [comment]
You’ve run into the most popular Python pitfall there is. :)

Writing `x = attr.ib(default=[])` is like writing `__init__(self, default=[])` which means there’s only one instance of list that is created when the *class* A is created and it's shared by all instances auf A.

What you want is `x = attr.ib(default=attr.Factory(list)`.

**Comment by ryantuck** [comment]
Ah yes that did the trick! 

For anyone else, the corrected class definition for `A` specifically should read:

```python
@attr.s
class A(object):

    x = attr.ib(default=attr.Factory(list))
```
