### ISSUE TITLE
Proposal: nice way to write ad-hoc validators

### ISSUE THREAD

**Issue by bluetech** [hynek/attrs#143]
Hopefully this wasn't proposed before.

```
@attr.s
class C(object):
    x = attr.ib()
    y = attr.ib()

    @x.validator                                               
    def x_smaller_than_y(self, attribute, value):
        if value >= self.y:
            raise ValueError("'x' has to be smaller than 'y'!")
```

If you managed to guess what this does it means the syntax is intuitive enough :)

Similar syntax familiar from `property.deleter` and friends can also be useful for other parts, but for validators it feels like a natural fit (especially with the recent change to allow multiple validators).

**Comment by hynek** [comment]
That looks interesting indeed!

**Comment by hynek** [comment]
fixed in 37d38c4dc3f6235992698ac5caaf0565517a3125

**Comment by xguse** [comment]
My question is: why is `attribute` included? It is not used in the validator function. What purpose does this serve?  How would it be used. The docs at this opint make it seem like this is required for the api to work but it is just ignored in the example given.

Can someone provide an example where `attribute` is used to illustrate the logic to me?

**Comment by bluetech** [comment]
The `validator` argument to [`attr.ib`](http://www.attrs.org/en/stable/api.html#attr.ib), which preceded the decorator, takes the same arguments. So the decorator takes them for consistency.

**Comment by hynek** [comment]
Yep that's the reason.  Internally they're treated the same.  We could add some magic to make it optional I guess but no one bothered so far.
