### ISSUE TITLE
Provide a way to have attributes that have an inital value, but no keyword argument.

### ISSUE THREAD

**Issue by tomprince** [hynek/attrs#19]
Given that `attrs` doesn't allow composing with a custom `__init__`, there is no way to initialize mutable implementation details.

For example,
```python
class Pool(object):
   def __init__(self, pool_size):
       self.pool_size = pool_size
       self._pool = []
    ...
```
can't be expressed with attrs.

**Comment by hynek** [comment]
`_pool = attr.ib(default=attr.Factory(list))` is what I use.

Maybe I could support `init=False` such that it’s actually impossible to pass values for it?  In my internal software I don’t care and just don’t pass anything, but if you’re building public APIs I see the value.

OTOH, I have written custom `__init__`s before.  In the end it’s more readable than giving 1000s of options and variations to hit every single edge-case.

**Comment by hynek** [comment]
Is #32 an adequate solution to your problem?

**Comment by tomprince** [comment]
It looks like it is.
