### ISSUE TITLE
Re-usable ordering decorator

### ISSUE THREAD

**Issue by jml** [hynek/attrs#23]
There are some circumstances where I would like to add comparison, or hashability, without wanting to decorate my class with attrs. 

`_add_cmp` and friends are very close to be generally useful. If they were made public, and the _attrs_to_tuple helper took an iterable of strings rather than `Attribute` objects, they'd be fully generic. 

Would you consider a patch that allowed this?

**Comment by hynek** [comment]
Subclass?  What attrs are you using actually? :)

**Comment by jml** [comment]
I meant "decorate with", not "subclass from". Sorry.

**Comment by hynek** [comment]
Um so I wouldn’t want to add any complexity in order to allow the usage of attrs without attr.s…so I guess I’d have to see the patch before making a decision.  But I’m rather -0 TBH.

**Comment by jml** [comment]
No worries. That helps a lot—I'll pursue other means.
