### ISSUE TITLE
Allow conversion of parameters

### ISSUE THREAD

**Issue by radix** [hynek/attrs#26]
I'd personally be able to get rid of a lot of boilerplate (either at call sites or as `__init__` methods) from my classes if attrs allowed me to supply a conversion callable with my `attr.ib`s. 

e.g.

```python
from pyrsistent import pmap

@attr.s
class Foo(object):
    mapping = attr.ib(coerce=pmap)
```

The `coerce` argument (naming to be bikeshedded) would be called with the value passed in after validation, and the return value would be used as the actual attribute value.

Would such a feature be accepted as a patch?

**Comment by radix** [comment]
or... maybe coerce should happen before validation. maybe that is one reason why this hasn't been done yet :)

**Comment by hynek** [comment]
Maybe a more generic name like "hook" would be more apt?

**Comment by econchick** [comment]
Omg I need this feature. NEED.
