### ISSUE TITLE
Multi-level inheritance: duplicate arguments in ctors

### ISSUE THREAD

**Issue by aldanor** [hynek/attrs#33]
A seemingly harmless example:

```python
@attr.s
class Foo(object):
    a = attr.ib()

@attr.s
class Bar(Foo):
    pass

@attr.s
class Baz(Bar):
    pass
```

fails with

```sh
  File "<attrs generated init 5250a51181cb781b2576810943a33169c4fea664>", line 1
SyntaxError: duplicate argument 'a' in function definition
```

Looks like `attrs` tries to include `a` twice in parameter list of `Baz#__init__`?

(possibly related: #24)

**Comment by hynek** [comment]
That looks like the same bug as #24 and your example works fine for me.  Are you using an old release by accident?  Check `attr.__version__` please, it should be 15.2.0.

**Comment by aldanor** [comment]
Whoah, indeed -- I had 15.1 installed, and it now works perfectly fine on 15.2 :+1: Sorry for the hassle!
