### ISSUE TITLE
Smarter validators?

### ISSUE THREAD

**Issue by aldanor** [hynek/attrs#34]
@hynek 
This is not a bug report or an issue, but rather a question of whether support for more intelligent / composable validators would be accepted?

In the latest project where I have a few dozen different classes in the schema, I made a bunch of wrappers around validators (e.g. so you don't have to type `attr.validators.instance_of` every time, and a few other simplifications), I'll provide a few lines of sample code below:

```python
fields_start = typed(non_negative(int), default=0)
checks = typed(list_of(Check), default=attr.Factory(list))
values = typed(non_empty(dict_of(non_empty(str), int)))
```

Here `typed` is a very lightweight wrapper around `attr.ib`. All of the validators here are fully composable, plus any type-like objects found where a validator is expected are automatically converted to `instance_of` (why else would you pass a type object to `validator` argument?). Would you be interested in extending validators in this way? If so, I could try and pack some of this up into a PR :smile_cat:

**Comment by hynek** [comment]
Your stuff sounds interesting and I think I’d totally may use it.  But I made attrs lightweight and composable for a reason (and it’s obviously working! :)).  Bluntly said I don’t want to maintain it.  But I’d happily link to it if you [put it on PyPI](https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/) yourself!  Something like `attrs_validators` or something?  That would have the advantage that you retain control over it and don’t have to convince me about every change you’d like to do.
