### ISSUE TITLE
attr.ib(init=False, default=...) doesn't seem to work

### ISSUE THREAD

**Issue by mithrandi** [hynek/attrs#36]
I'm not sure what's going on here, but the docs seem to suggest that it's a bug:
```
>>> import attr
>>> @attr.s
... class Foo(object):
...     bar = attr.ib(init=False, default=42)
... 
>>> Foo().bar  # Should be 42
_CountingAttr(counter=6, default=42, repr=True, cmp=True, hash=True, init=False)
```

**Comment by mithrandi** [comment]
Oh I see, this was only made possible in 1af3eaa877ea1bfa376370914ffa135c1a10cad9 which isn't released yet. Could we get a release? :heart_eyes:

**Comment by hynek** [comment]
Hahaha I was just looking up #32. :)

Release will follow after #35 is merged (basically just docs open; feel free to look over the code/design!) and I’d like to find a resolution for #25.

I think you asked about that on IRC when I was on vacation?

**Comment by mithrandi** [comment]
Ah, yes; I was confused, because #25 went in a bit of a different direction than the title suggests.

**Comment by mithrandi** [comment]
(but I think #32 subsumes all of my needs for the thing I initially asked for, so...)

**Comment by hynek** [comment]
I’m closing this and I’ll try to get out a release ASAP.  The slots ticket is almost done, #25 shouldn’t take too long.
