### ISSUE TITLE
Support passing the dict class to asdict

### ISSUE THREAD

**Issue by Tinche** [hynek/attrs#40]
A feature idea: attr.asdict currently turns classed into ordinary Python dicts. It'd be useful if a dict factory could be passed in (defauting to just `dict`). The main use case would be to pass in OrderedDict.

I have a situation at work that this would be useful for, but we're approaching the problem from a different angle so we probably won't need it. Just thought it might be a useful feature and simple to implement. I could put together a pull request.

**Comment by hynek** [comment]
I guess it might be worth it if it doesn’t add too much complexity.  Retaining the order of the attributes sounds like a good thing.

**Comment by Tinche** [comment]
Fixed by #42.
