### ISSUE TITLE
Convert readthedocs link for their .org -> .io migration for hosted projects

### ISSUE THREAD

**Issue by adamchainz** [hynek/attrs#46]
The link on the Github repo description needs updating for the RTD migration, as per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:

> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.

https://attrs.readthedocs.io/en/stable/ is where one now ends up

**Comment by hynek** [comment]
thanks,  fixed.
