### ISSUE TITLE
Unclear documentation for attr.ib's default

### ISSUE THREAD

**Issue by salty-horse** [hynek/attrs#53]
* Please explain what `default=NOTHING` means, specifically that it will require the caller to specify a value(?)

* >If the value an instance of `Factory`, it callable will be use to construct a new value.

 "it callable" feels like a typo. Should probably be "its callabe".

**Comment by hynek** [comment]
I believe I’ve fixed it.  How does http://attrs.readthedocs.io/en/latest/api.html#attr.ib look to you?

**Comment by salty-horse** [comment]
Good, thanks! But I noticed another problem in the same sentence that I missed before:

"its callable will be use" -> "used" :stuck_out_tongue:

**Comment by hynek** [comment]
m(

Thanks for reporting it. :)
