### ISSUE TITLE
Small suggestions about Examples

### ISSUE THREAD

**Issue by salty-horse** [hynek/attrs#59]
* The Slots section mentions "instance variables". This is not a Python term. Consider using "data attribute" (although that may confuse with `attrs`' `Attribute`?)

* The double-hyphen (`--`) in the beginning of the document doesn't turn into a dash in ReST. Replace it with a literal em-dash: —.

* The list in Validators has odd capitalization/punctuation:
    >```
    >#. The *instance* that's being validated.
    >#. The *attribute* that it's validating
    >#. and finally the *value* that is passed for it.
    >```

    I think this is better punctuation:
    ```
    #. the *instance* that's being validated,
    #. the *attribute* that it's validating, and finally
    #. the *value* that is passed for it.
    ```

* In the example about Defaults, the comment here confused me for a moment:
    >```python
    >def connect(cls, db_string):
    >     # connect somehow to db_string
    >     return cls(socket=42)
    >```

    I read it as describing the line below it, rather than being a placeholder. Maybe this would be more intuitive:
    ```python
    # ... connect somehow to db_string ...
    ```

* The Examples page is great, but I'm missing direct links to the API docs, in case I want to learn more about specific features. I found myself ctrl-F-ing the API documentation manually. Maybe such links would clutter the page — not sure I have a good solution.

**Comment by hynek** [comment]
I believe I’ve addressed everything except:

- which `--`?  there was one very pointless that I’ve removed but it rendered fine for me?
- not sure what to do about the API docs since 99% of the links would point to `attr.s` or `attr.ib`?  Most others seem to be linked.

**Comment by salty-horse** [comment]
I used github's renderer for the file, which kept "--" as "--". Maybe it works fine.

You're right, most of the examples refer to arguments of `attr.ib`, and I don't think it's possible to link to a particular flag's documentation. However, `assoc` is a function. The only link in that section is to Clojure :)

**Comment by hynek** [comment]
I believe I’ve caught them all. :)

As for `--`: GitHub's renderer is just reST which ist just a sub-set of Sphinx which leads to regular surprises 🎉.
