### ISSUE TITLE
stay positive!

### ISSUE THREAD

**Issue by wbolster** [hynek/attrs#6]
Please consider avoiding double negatives in arguments... pretty please? `no_xyz=False` makes my head asplode. `xyz=True` is a lot more clear.

**Comment by hynek** [comment]
Yeah I’ve been struggling with this.

- `repr=True` will clash with the builtin
- `no_repr` makes a stronger case what the desired default is

I have to admit that I’m completely unhappy & undecided yet. :-/

**Comment by wbolster** [comment]
TBH `no_repr=False` doesn't make a case about desired defaults at all for me; it just confuses me.

Having an arg clash with a built-in is not a problem at all. For example, there are `type=` args all over the place in many libs, also in the stdlib. It's much nicer for consumers of the API, and the caveats about overwriting built-ins only apply to the internal implementation of the lib. The lib itself can always make a module level alias like `builtin_repr = repr` (or access it through `__builtins__` but that's a bit ugly).

Alternatively, include a verb, e.g. `include_repr`, `add_repr`, `use_repr`.

**Comment by hynek** [comment]
so…much…manual…work 😭

**Comment by wbolster** [comment]
The defaults should make sense, so most users won't touch it, right?

**Comment by hynek** [comment]
right. but manual work for me now to search/replace and flip the logic

**Comment by wbolster** [comment]
Poor you. The miserable life of an OSS maintainer. I feel your pain. ;-)

But this new positive attitude in your code surely raised your karma.

**Comment by econchick** [comment]
I loved this exchanged :heart:
