### ISSUE TITLE
C.asdict() rather than attr.asdict(C)

### ISSUE THREAD

**Issue by kootenpv** [hynek/attrs#67]
I believe that this can avoid having to import attr at other places. Naturally, people could just simply overwrite this themselves, but it would be nice as an attribute of an attr class.

**Comment by kootenpv** [comment]
Concretely, instead of:

    attr.asdict(C)

use:

    C.asdict()

**Comment by hynek** [comment]
The reason why asdict is a function instead of a method is that attrs first an foremost tries to be “regular Python class”.  Therefore we try to add as little as possible to the overall shape of a class.

If you want asdict *on* the instances, it’s one line of code:

```pycon
>>> @attr.s
... class C:
...     x = attr.ib()
...     y = attr.ib()
...     asdict = attr.asdict

>>> C(1,2).asdict()
{'y': 2, 'x': 1}
```
