### ISSUE TITLE
asdict(): Optionally retain collection types

### ISSUE THREAD

**Issue by vortec** [hynek/attrs#69]
When calling `attr.asdict()`, it converts attributes of type `tuple`, `set` to type `list` and subclasses of `dict` to `dict`. This is being done for JSON compatibility, however, there are use cases where it's required to preserve the original type.

Therefore I request an optional argument called `retain_collection_types`, which is set to `False` by default (to not break the existing API). If enabled, the function should not convert any collection type.

**Comment by Tinche** [comment]
How about we just use the `__class__` of the collection by default?

```
            elif isinstance(v, (tuple, list, set)):
                rv[a.name] = v.__class__(
                    asdict(i, recurse=True, filter=filter,
                           dict_factory=dict_factory)
                    if has(i.__class__) else i
                    for i in v
                )
```

```
>>> @attr.s
... class T:
...     x = attr.ib()
>>> attr.asdict(T((1,2,3)))
{'x': (1, 2, 3)}
>>> attr.asdict(T(set([1,2,3])))
{'x': {1, 2, 3}}
>>> attr.asdict(T([1,2,3]))
{'x': [1, 2, 3]}
```
