### ISSUE TITLE
Instantiated attributes cannot have their values updated...

### ISSUE THREAD

**Issue by sseg** [hynek/attrs#72]
...while keeping the attr.ib validators.

I'd like to be able to create a class:

    >>> @attr.s
    >>> class Obj:
    >>>     a = attr.ib(validator=attr.validators.instance_of(str))

Instantiate it:

    >>> obj = Obj('1')

And then update instantiated attributes but have these updates subject to existing validators:

    >>> obj.a = 1
    TypeError: 'a' must be <class 'str'>

Maybe this could be achieved by means of a helper function? Something like:

    >>> attr.update(obj, a=1)

Is this kind of behavior something that people are interested in?

**Comment by Tinche** [comment]
Well, there's `validate()` (https://attrs.readthedocs.io/en/stable/api.html#attr.validate), you could manually call it after mutating.

**Comment by sseg** [comment]
Ah perfect, thanks @Tinche, this will work quite well for my use-case.

**Comment by hynek** [comment]
I guess I can close this then. :)
