### ISSUE TITLE
astuple method

### ISSUE THREAD

**Issue by Insoleet** [hynek/attrs#77]
Hello,

For the usage of attr with DB API 2.0 libraries (like Sqlite3), it would be great to have a `astuple` method.

This method would return the object values in a tuple, ordered by the order of declaration of it's attributes.

For example we could do things like this : 

```python
import sqlite3
import attr

@attr.s()
class Foo:
    a = attr.ib()
    b = attr.ib()

foo = Foo(2, 3)
con = sqlite3.connect(":memory:")
with con:
    con.execute("INSERT INTO foo VALUES (?, ?)", attr.astuple(foo))
```

This would be useful for DB API libraries but also for other needs probably.

What is your opinion about it ?

**Comment by hynek** [comment]
Your use case is compelling indeed.  `attr.asdict(foo).values()` probably gets old.  Unless @glyph tells me a good reason against, I would allow it.

**Comment by Tinche** [comment]
``attr.asdict(foo).values()`` wouldn't even work unless you used an ordered dict :)

**Comment by Tinche** [comment]
I think this would be a nice mirror to asdict. Also a tuple of values will be more efficient than a dict if you can use this.

@Insoleet Would you like to implement this? It's relatively easy and more contributors is always good :) I can do a preliminary review before @hynek.

**Comment by Insoleet** [comment]
I'd be glad to add my commit to this wonderful library ;) I'll try to submit a pull request during the week.

**Comment by Insoleet** [comment]
How do you think that `dict` `set` `list` `tuple` should be handled by the astuple method ? Using deepcopy ? Using references ? Or something else ?

**Comment by hynek** [comment]
does recursing make even sense with tuples? oO

**Comment by Tinche** [comment]
We should probably try to mirror `asdict`.

For nested attr classes, this would be:
```
@attr.s
class A:
    b = attr.ib()

@attr.s
class B:
    c = attr.ib()

>>> a = A(B(1))
>>> 
>>> attr.asdict(a)
{'b': {'c': 1}}
>>> attr.asdict(a, recurse=False)
{'b': B(c=1)}
>>> attr.astuple(a)
((1,),)
>>> attr.astuple(a, recurse=False)
(B(c=1),)
```

For built-in collections... Just do what ``asdict`` does?

```
>>> attr.asdict(A([B(1), B(2), B(3)]))
{'b': [{'c': 1}, {'c': 2}, {'c': 3}]}
>>> attr.astuple(A([B(1), B(2), B(3)]))
([(1,), (2,), (3,)],)
```

Another side of the mirroring: an non-nested attr class can be dumped and loaded like this:
```
b = B(1)
b == B(**attr.asdict(b))
```
so tuples work in a similar way:
```
b = B(1)
b == B(*attr.astuple(b))
```

Thoughts?
