### ISSUE TITLE
attr.filters.include/exclude don't work with attributes on slots classes

### ISSUE THREAD

**Issue by rouge8** [hynek/attrs#82]
`attr.filters.include`/`attr.filters.exclude` don't work with attributes as expected from the docs on classes where `slots=True`.

```python
import attr

@attr.s(slots=True)
class Foo(object):
    bar = attr.ib()
    baz = attr.ib()

f = Foo(bar=1, baz=2)

assert attr.asdict(f, filter=attr.filters.exclude(Foo.bar)) == {'baz': 2}
```

**Comment by hynek** [comment]
OK this is a “fun” one in multiple ways.

- include and exclude take advantage of the fact that classes have the `Attribute`s attached to them which I’ve deprecated in 16.1.  I completely forgot about the filters module TBH.  Meaning if we go through with it, you’d have to go via `Foo.__attrs_attrs__` (or we write some helper function).
- they do an `isinstance(..., Attribute)` to detect it’s an `Attribute` which fails with slots that returns an `<class 'member_descriptor'>`.

Therefore as far as I see it:

1. this feature in this form is literally impossible for ``__slots__`` classes and should be documented as such.
2. we need to deprecate them and replace them with a new API.

I’m happy to be corrected.

I’m sorry. :(

**Comment by hynek** [comment]
Fixed, please use `attr.fields(Foo).bar` once 16.2.0 is out.

**Comment by rouge8** [comment]
Awesome, thanks!

**Comment by cosmosgenius** [comment]
> Fixed, please use `attr.fields(Foo).bar` once 16.2.0 is out.

We should add this as an example for exclude and include...it was confusing from documentation on how to use the filter.

**Comment by Murtagy** [comment]
@hynek I think there is yet no reference for this in the docs.

To prefer using 
```
field = attrs.fields(model_obj.__class__)
fields.field_name
```
over 
```
fields[0] # (which you might generated from list compehension)
# e.g
no_fields = [f for f in fields if f.metadata.get('auto') is True]
attrs.filters.exclude(no_fields)  # does absolutely nothing for slotted class
```

**Comment by hynek** [comment]
@cosmosgenius there is an example in https://www.attrs.org/en/stable/examples.html#converting-to-collections-types

@Murtagy I'm sorry but I'm not sure what exactly you mean, but it doesn't seem to be related to the original problem of accessing Attribute objects directly on classes (which doesn't work for 5 years now).

**Comment by Murtagy** [comment]
Here is full example of the misleading behaviour I faced:
 
 ```python3 
import attr

@attr.s
class A:
    a: int = attr.ib(metadata={'allow_me': True})
    b: int = attr.ib(metadata={'filter_me_out': True})

a = A(1,2)

fields = attr.fields(A)
filter_these_out = [f for f in fields if f.metadata.get('filter_me_out') is True]

attr.astuple(a, filter=attr.filters.exclude(filter_these_out),)
# >> (1,2)
# expected only (1,)

# line below works as I expected
attr.astuple(a, filter=lambda _attr, val: _attr not in filter_these_out)
# >> (1,)
 ```

`exclude` definition tells to pass in a list of attributes to exclude, so I expected the upper behavior.
```
def exclude
    Exclude *what*.

    :param what: What to exclude.
    :type what: `list` of classes or `attrs.Attribute`\\ s.
```
Not sure wether I should open an issue for it.

**Comment by hynek** [comment]
@Murtagy heh this took me a second to figure out too! `exclude` take `*what`, not `what`.

IOW: `attr.astuple(a, filter=attr.filters.exclude(*filter_these_out),)` works as expected.
