### ISSUE TITLE
Edit on github link not working

### ISSUE THREAD

**Issue by hanpari** [hynek/attrs#92]
Hi,

on documentation page *https://attrs.readthedocs.io/en/stable/* there is Edit on Github. After clicking I got **not found page** for given link:

*https://github.com/hynek/attrs/blob/8b01207df4ee9e8b88da5fed218f62e17e3bb812/docs/index.rst*

**Comment by Tinche** [comment]
Can confirm, I noticed this before. :)

**Comment by hynek** [comment]
Not sure what I can do about that?

**Comment by Tinche** [comment]
I figured 8b01207df4ee9e8b88da5fed218f62e17e3bb812 would be a commit hash but there's no commit with that hash that I can see. 🤔

**Comment by Tinche** [comment]
If on readthedocs you pick 'latest' instead of 'stable', the links point to master and that's OK.

**Comment by hynek** [comment]
I have literally this issue open on every project of mine and I have no idea what to do about it. :(
