### ISSUE TITLE
IDE completion for __init__ arguments and more

### ISSUE THREAD

**Issue by vtexier** [hynek/attrs#94]
When `attrs` is used, IDE completion for `__init__` arguments is broken.
And, may be, some other completion.

Would it be possible to get back a minimal IDE completion for `__init__` arguments ?
And, may be, generate a minimal doc-string documentation of the class and attributes...

**Comment by hynek** [comment]
There is no “the IDE” :) every IDE handles it differently and I suspect mostly through static analysis which of course fails if the method is never written out.

But the data is all there, you’ll just have to convince your IDE vendor to support attrs.  There is nothing *we* can do.

**Comment by jamescasbon** [comment]
> But the data is all there, you’ll just have to convince your IDE vendor to support attrs

Many ides use jedi which seems broken for both dataclasses and atrs: davidhalter/jedi#1213 
I've pointed out on that ticket that the data is in __annotations__

> There is nothing we can do.

Well, you could generate an __init__ that actually has the arguments in it rather than *args, **kws style?

**Comment by Tinche** [comment]
> Well, you could generate an init that actually has the arguments in it rather than *args, **kws style?

We do already, but thanks for the suggestion :)

**Comment by jamescasbon** [comment]
> We do already, but thanks for the suggestion :)

So you do, sorry.  I could have sworn I did inspect.getsource and saw a *a, **kw style but clearly my memory is fallible.

Does raise the question why jedi is so bad at completing them :/

**Comment by hynek** [comment]
> Does raise the question why jedi is so bad at completing them :/

I think they're parsing and not evaluating?

**Comment by glyph** [comment]
@hynek This works correctly for the stdlib and not for attrs in jedi, so I filed https://github.com/davidhalter/jedi/issues/1835
