### ISSUE TITLE
Don't overwrite name with qualname for slots classes

### ISSUE THREAD

**Issue by rdpate** [hynek/attrs#99]
For slots classes, [attr._make.attributes](https://github.com/hynek/attrs/blob/ca2a1e10f01175869edaf06b5b4b208de283254f/src/attr/_make.py#L288) overwrites \_\_name\_\_ with \_\_qualname\_\_.  This shouldn't happen on Python 3.  (Nothing happens on Python 2, as \_\_qualname\_\_ is never set.)  I think the correct fix is to change:

    if repr_ns is None:
        cls_name = getattr(cls, "__qualname__", cls.__name__)
    else:
        cls_name = cls.__name__

    cls = type(cls_name, cls.__bases__, cls_dict)

To:

    cls = type(cls.__name__, cls.__bases__, cls_dict)

However, this [doesn't preserve qualname](https://github.com/rdpate/attrs/commit/498709561f5785f0defc76c916eef91c29433708), and I fear I'm missing something else.

**Comment by hynek** [comment]
I’m sure there’s a reason and @Tinche will tell us the reason. :)  Seems like there’s some edge case around it.  We should definitely add a comment to clear it up.

**Comment by Tinche** [comment]
The reason is probably I messed it up by accident and there was no test. :)

I'll take a look later today.

**Comment by rdpate** [comment]
Now there is a test, in my second link. :) I tried to run tox and submit this as a pull-request, but tox crashed when it ran pip freeze, which crashed because FreeBSD has a system module named "_sqlite3" (which is used by the stdlib module sqlite3).

**Comment by Tinche** [comment]
I noticed and stole your test. :)

**Comment by rdpate** [comment]
The previous test has a bug: qualname, of course, includes the test class and function.  Also, saving and setting qualname seems to be the only other action required.  (I did get tox -epy24,py34,py35 to run on another machine and the only failures were slow data generation for hypothesis.)

https://github.com/rdpate/attrs/commit/e64d22dd7d4411b0345b317073038f8998f2d149

**Comment by Tinche** [comment]
Great. How about you submit a pull request and we can switch the discussion to there? We're always eager for new contributors. :)

**Comment by rdpate** [comment]
https://github.com/hynek/attrs/pull/100
